version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: ineedtoilet-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ineedtoilet
      POSTGRES_USER: captain
      POSTGRES_PASSWORD: password123
      TZ: Asia/Seoul
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always